### ISSUE TITLE
Move alternates initialization out of autoload

### ISSUE THREAD

**Issue by davidvandebunte** [LucHermitte/alternate-lite#5]
When I started setting this project up, it looked like I'd only need to change `alternates.searchpath`:
```vimscript
let g:alternates.searchpath='sfr:.,reg:|\(\a\+\)/include/\a\+|\1/src|g|,reg:|\(\a\+\)/src|\1/include/\1|g|'
```

Unfortunately this produces an error:
```vimscript
E121: Undefined variable: g:alternates
```

My workaround was to call a function that led to the autoload scripts running:
```vimscript
call lh#alternate#register_extension('g', 'h', ['hpp', 'cpp'])
```

It seems like it would be reasonable to move the initialization of `alternates` to the main script to avoid this for other users.

**Comment by LucHermitte** [comment]
There are two problems here: 
- The one you've experienced (`let var.key = ...` which is not supported on new variables), 
- The hidden one where whatever you set would be overridden in the autoload plugin, because I've used `lh#let#to()` instead of `lh#let#if_undef()`.

So far, I've been expecting (for the first problem) the end-user to either use `lh#let#to()` or `:LetTo`. In `searchpath` specific case I can indeed move it out to the plain-plugin. However, I won't move the other settings out of the autoload plugin as it would defeat the purpose of using autoload plugins.

Still, you won't be able to write `let g:alternates.searchpath='sfr....` before your plugin manager has registered and loaded alternate-lite. I cannot do anything here except reverting of my decision of using a dictionary to store plugin settings.
